### ISSUE TITLE
Music Playing Throughout game

### ISSUE THREAD

**Issue by emaul** [ErvinM/CS245Android#1]
Music playing continuously despite rotation

**Comment by garcia0jose** [comment]
I wasn't exactly sure where tom place my current progress within the program, and I'm still working on parts of it, but I made 2 styles of the music utilizing class that would allow the state of music to be saved. my first one was more close to the slides with the saveInstanceState, the second utilized looping and volume control (wasn't sure if that was necessary) in the onCreate method instead

STYLE 1:
public class AudioPlayer extends Object
{
    private MediaPlayer mPlayer;

    public void stop()
    {
        if(mPlayer != null)
        {
            mPlayer.release();
            mPlayer = null;
        }
    }
    public void play(Context c)
    {
        mPlayer = MediaPaler.create(c, R.raw.one_small_step);
        mPlayer.start();
    }

    public void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);

        mPlayer = new MediaPlayer(getActivity);
    }

}
STYLE 2:

public class AudioPlayer extends Object
{
    private MediaPlayer mPlayer;

    public void play(Context c)
    {
        mPlayer = MediaPaler.create(c, R.raw.one_small_step);
        mPlayer.start();
    }

    public void stop()
    {
        if(mPlayer != null)
        {
            mPlayer.release();
            mPlayer = null;
        }
    }
    public void onCreate() 
    {
        super.onCreate();
        mPlayer = MediaPlayer.create(this, R.raw.idil);
        mPlayer.setLooping(true); // Set looping
        mPlayer.setVolume(100,100); //necessary?

    }
    public void onDestroy() 
    {
        mPlayer.stop();
        mPlayer.release();
    }
}
